### PR TITLE
Signoff for Server Hardware

### PR DESCRIPTION
**Pull request by kesternucum**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
It doesn't seem like the AI algorithm's processing has been considered. This must be characterized for the constraints and analysis to be meaningful.

**Review by JesseTNRoberts — COMMENTED** [review]
This looks good. I am curious if you have looked for anything off the shelf that could be used instead?

**Comment by kesternucum** [comment]
> This looks good. I am curious if you have looked for anything off the shelf that could be used instead?

Yes, I have, though I've determined that it would be cheaper to order all parts individually rather than buy a pre-built PC. In addition, building a PC from scratch is known to be generally cheaper than pre-built parts due to the ability for us to hand-select parts, especially since we need a mid-tier GPU. In addition, a laptop, even the most efficient gaming laptops, most likely would not have sufficient graphics unit abilities to handle the amount of real-time image processing we're planning on doing--if so, that laptop would be over $1000. Other laptops that have a NVIDIA GPU that meets our constraints don't have sufficient CPU, memory, or operating system already booted on.

For example, this PC with an AMD Ryzen 5 3600 (which we need due to its number of threads) and a NVIDIA RTX 2060 (which has higher performance than the GTX 1650 which is what I had put down) is $879.99: [https://skytechgaming.com/product/0431-gaming-desktop-intel-nvidia-3050/](https://skytechgaming.com/product/0431-gaming-desktop-intel-nvidia-3050/).

Should this be addressed in the sign-off?

**Comment by kesternucum** [comment]
I also just found that the cheapest option I could find regarding gaming PCs with a mid- to high-end NVIDIA GPU and a Intel i5 6-core processor is roughly $1000: https://www.amazon.com/GIGABYTE-G5-KD-i5-11400H-KD-52US123SO/dp/B09QPT6TZJ. It's still cheaper to purchase parts individually than a preassembled laptop or PC.

**Review by JesseTNRoberts — APPROVED** [review]
This looks good. I have a pc that we can use for initial testing. So, we will not purchase this immediately. Rather, we will get the system running on a cheaper system and then it can be migrated to a more powerful PC once the department works out what that looks like with IT.

**Pull request merged**
